### ISSUE TITLE
Delete an extra files and directories

### ISSUE THREAD

**Issue by mamadaliev** [Hardelele/cargo-transportation#2]
Hello, @Hardelele! How are you?

I think that your project has additional files and directories, please delete them if you think this is correct:
- .idea/
- IELapshin.iml

Also, please write in your `.gitignore` this code (for ignoring an extra files):
```
.idea/
*.iml
```

Please, not mark as spam this issue. Thanks. Good luck! ✊🏻

**Comment by Hardelele** [comment]
Yo, @egnaf. I am ok. 

You right! I'll do this as soon as a free minute appears. 

ty&gl!

**Comment by mamadaliev** [comment]
@Hardelele It's been 12 days, but you haven't done it yet. How so?
